// Copyright (c) 2026 AOR Conseil — proprietary, see LICENSE.md.

export const INVITE_TOKEN_VALIDATION_USE_CASE_SYMBOL = Symbol('INVITE_TOKEN_VALIDATION_USE_CASE_SYMBOL');
export const GET_INVITE_PREVIEW_USE_CASE_SYMBOL = Symbol('GET_INVITE_PREVIEW_USE_CASE_SYMBOL');
export const SUBMIT_INVITE_QUESTIONNAIRE_USE_CASE_SYMBOL = Symbol('SUBMIT_INVITE_QUESTIONNAIRE_USE_CASE_SYMBOL');
export const ACTIVATE_INVITE_WITH_PASSWORD_USE_CASE_SYMBOL = Symbol('ACTIVATE_INVITE_WITH_PASSWORD_USE_CASE_SYMBOL');
export const CONFIRM_INVITE_PARTICIPATION_USE_CASE_SYMBOL = Symbol('CONFIRM_INVITE_PARTICIPATION_USE_CASE_SYMBOL');
