// Copyright (c) 2026 AOR Conseil — proprietary, see LICENSE.md.

export const PARTICIPANT_LOGIN_USE_CASE_SYMBOL = Symbol('PARTICIPANT_LOGIN_USE_CASE_SYMBOL');
export const SUBMIT_PARTICIPANT_QUESTIONNAIRE_USE_CASE_SYMBOL = Symbol(
    'SUBMIT_PARTICIPANT_QUESTIONNAIRE_USE_CASE_SYMBOL'
);
export const GET_PARTICIPANT_OWNED_RESPONSE_USE_CASE_SYMBOL = Symbol('GET_PARTICIPANT_OWNED_RESPONSE_USE_CASE_SYMBOL');
export const GET_PARTICIPANT_SESSION_USE_CASE_SYMBOL = Symbol('GET_PARTICIPANT_SESSION_USE_CASE_SYMBOL');
export const GET_PARTICIPANT_SESSION_QUESTIONNAIRE_MATRIX_USE_CASE_SYMBOL = Symbol(
    'GET_PARTICIPANT_SESSION_QUESTIONNAIRE_MATRIX_USE_CASE_SYMBOL'
);
export const LIST_PARTICIPANT_CAMPAIGN_PEERS_USE_CASE_SYMBOL = Symbol(
    'LIST_PARTICIPANT_CAMPAIGN_PEERS_USE_CASE_SYMBOL'
);
