// Copyright (c) 2026 AOR Conseil — proprietary, see LICENSE.md.

export const ADMIN_AUTH_USE_CASE_SYMBOL = Symbol('ADMIN_AUTH_USE_CASE_SYMBOL');
export const GET_ADMIN_DASHBOARD_USE_CASE_SYMBOL = Symbol('GET_ADMIN_DASHBOARD_USE_CASE_SYMBOL');
export const LIST_ADMIN_RESPONSES_USE_CASE_SYMBOL = Symbol('LIST_ADMIN_RESPONSES_USE_CASE_SYMBOL');
export const DELETE_ADMIN_RESPONSE_USE_CASE_SYMBOL = Symbol('DELETE_ADMIN_RESPONSE_USE_CASE_SYMBOL');
export const LIST_ADMIN_PARTICIPANTS_USE_CASE_SYMBOL = Symbol('LIST_ADMIN_PARTICIPANTS_USE_CASE_SYMBOL');
export const IMPORT_PARTICIPANTS_CSV_USE_CASE_SYMBOL = Symbol('IMPORT_PARTICIPANTS_CSV_USE_CASE_SYMBOL');
export const CREATE_PARTICIPANT_INVITE_USE_CASE_SYMBOL = Symbol('CREATE_PARTICIPANT_INVITE_USE_CASE_SYMBOL');
export const LIST_PARTICIPANT_INVITATION_TOKENS_USE_CASE_SYMBOL = Symbol(
    'LIST_PARTICIPANT_INVITATION_TOKENS_USE_CASE_SYMBOL'
);
export const ERASE_PARTICIPANT_RGPD_USE_CASE_SYMBOL = Symbol('ERASE_PARTICIPANT_RGPD_USE_CASE_SYMBOL');
export const GET_ADMIN_MAIL_STATUS_USE_CASE_SYMBOL = Symbol('GET_ADMIN_MAIL_STATUS_USE_CASE_SYMBOL');
export const LIST_ADMIN_COMPANIES_USE_CASE_SYMBOL = Symbol('LIST_ADMIN_COMPANIES_USE_CASE_SYMBOL');
export const GET_ADMIN_COMPANY_USE_CASE_SYMBOL = Symbol('GET_ADMIN_COMPANY_USE_CASE_SYMBOL');
export const CREATE_ADMIN_COMPANY_USE_CASE_SYMBOL = Symbol('CREATE_ADMIN_COMPANY_USE_CASE_SYMBOL');
export const UPDATE_ADMIN_COMPANY_USE_CASE_SYMBOL = Symbol('UPDATE_ADMIN_COMPANY_USE_CASE_SYMBOL');
export const DELETE_ADMIN_COMPANY_USE_CASE_SYMBOL = Symbol('DELETE_ADMIN_COMPANY_USE_CASE_SYMBOL');
export const EXPORT_ADMIN_RESPONSES_CSV_USE_CASE_SYMBOL = Symbol('EXPORT_ADMIN_RESPONSES_CSV_USE_CASE_SYMBOL');
export const EXPORT_ADMIN_ANONYMIZED_RESPONSES_CSV_USE_CASE_SYMBOL = Symbol(
    'EXPORT_ADMIN_ANONYMIZED_RESPONSES_CSV_USE_CASE_SYMBOL'
);
export const GET_PARTICIPANT_QUESTIONNAIRE_MATRIX_USE_CASE_SYMBOL = Symbol(
    'GET_PARTICIPANT_QUESTIONNAIRE_MATRIX_USE_CASE_SYMBOL'
);
export const LIST_ADMIN_CAMPAIGNS_USE_CASE_SYMBOL = Symbol('LIST_ADMIN_CAMPAIGNS_USE_CASE_SYMBOL');
export const LIST_ADMIN_COACHES_USE_CASE_SYMBOL = Symbol('LIST_ADMIN_COACHES_USE_CASE_SYMBOL');
export const CREATE_ADMIN_COACH_USE_CASE_SYMBOL = Symbol('CREATE_ADMIN_COACH_USE_CASE_SYMBOL');
export const GET_ADMIN_COACH_DETAIL_USE_CASE_SYMBOL = Symbol('GET_ADMIN_COACH_DETAIL_USE_CASE_SYMBOL');
export const UPDATE_ADMIN_COACH_USE_CASE_SYMBOL = Symbol('UPDATE_ADMIN_COACH_USE_CASE_SYMBOL');
export const DELETE_ADMIN_COACH_USE_CASE_SYMBOL = Symbol('DELETE_ADMIN_COACH_USE_CASE_SYMBOL');
export const CREATE_ADMIN_CAMPAIGN_USE_CASE_SYMBOL = Symbol('CREATE_ADMIN_CAMPAIGN_USE_CASE_SYMBOL');
export const UPDATE_ADMIN_CAMPAIGN_STATUS_USE_CASE_SYMBOL = Symbol('UPDATE_ADMIN_CAMPAIGN_STATUS_USE_CASE_SYMBOL');
export const REASSIGN_ADMIN_CAMPAIGN_COACH_USE_CASE_SYMBOL = Symbol('REASSIGN_ADMIN_CAMPAIGN_COACH_USE_CASE_SYMBOL');
export const GET_ADMIN_CAMPAIGN_DETAIL_USE_CASE_SYMBOL = Symbol('GET_ADMIN_CAMPAIGN_DETAIL_USE_CASE_SYMBOL');
export const INVITE_CAMPAIGN_PARTICIPANTS_USE_CASE_SYMBOL = Symbol('INVITE_CAMPAIGN_PARTICIPANTS_USE_CASE_SYMBOL');
export const IMPORT_PARTICIPANTS_TO_CAMPAIGN_USE_CASE_SYMBOL = Symbol(
    'IMPORT_PARTICIPANTS_TO_CAMPAIGN_USE_CASE_SYMBOL'
);
