// Copyright (c) 2026 AOR Conseil — proprietary, see LICENSE.md.

export const LIST_QUESTIONNAIRES_USE_CASE_SYMBOL = Symbol('LIST_QUESTIONNAIRES_USE_CASE_SYMBOL');
export const GET_QUESTIONNAIRE_DETAIL_USE_CASE_SYMBOL = Symbol('GET_QUESTIONNAIRE_DETAIL_USE_CASE_SYMBOL');
